        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE ASSIGNDATA__genmod
          INTERFACE 
            SUBROUTINE ASSIGNDATA
            END SUBROUTINE ASSIGNDATA
          END INTERFACE 
        END MODULE ASSIGNDATA__genmod
