        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE ASSIGNDATA1__genmod
          INTERFACE 
            SUBROUTINE ASSIGNDATA1
            END SUBROUTINE ASSIGNDATA1
          END INTERFACE 
        END MODULE ASSIGNDATA1__genmod
