        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE INFERCPDFDZ__genmod
          INTERFACE 
            SUBROUTINE INFERCPDFDZ(IX,IY,IZ,IMULT)
              INTEGER(KIND=4), INTENT(IN) :: IX
              INTEGER(KIND=4), INTENT(IN) :: IY
              INTEGER(KIND=4), INTENT(IN) :: IZ
              INTEGER(KIND=4), INTENT(IN) :: IMULT
            END SUBROUTINE INFERCPDFDZ
          END INTERFACE 
        END MODULE INFERCPDFDZ__genmod
