        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE RANDOMPATH__genmod
          INTERFACE 
            SUBROUTINE RANDOMPATH
            END SUBROUTINE RANDOMPATH
          END INTERFACE 
        END MODULE RANDOMPATH__genmod
