        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE READPARM__genmod
          INTERFACE 
            SUBROUTINE READPARM
            END SUBROUTINE READPARM
          END INTERFACE 
        END MODULE READPARM__genmod
