        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE RELOCATEDATA__genmod
          INTERFACE 
            SUBROUTINE RELOCATEDATA
            END SUBROUTINE RELOCATEDATA
          END INTERFACE 
        END MODULE RELOCATEDATA__genmod
