        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE SEARCHCLOSESTNODES__genmod
          INTERFACE 
            SUBROUTINE SEARCHCLOSESTNODES(IX,IY,IZ)
              INTEGER(KIND=4), INTENT(IN) :: IX
              INTEGER(KIND=4), INTENT(IN) :: IY
              INTEGER(KIND=4), INTENT(IN) :: IZ
            END SUBROUTINE SEARCHCLOSESTNODES
          END INTERFACE 
        END MODULE SEARCHCLOSESTNODES__genmod
