        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE SETROTMAT__genmod
          INTERFACE 
            SUBROUTINE SETROTMAT(IMULT)
              INTEGER(KIND=4), INTENT(IN) :: IMULT
            END SUBROUTINE SETROTMAT
          END INTERFACE 
        END MODULE SETROTMAT__genmod
