        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE SIMULATION__genmod
          INTERFACE 
            SUBROUTINE SIMULATION(IMULT)
              USE VARMOD
              INTEGER(KIND=4), INTENT(IN) :: IMULT
            END SUBROUTINE SIMULATION
          END INTERFACE 
        END MODULE SIMULATION__genmod
