        !COMPILER-GENERATED INTERFACE MODULE: Thu May 12 23:40:16 2022
        MODULE SORTTEMPLATE__genmod
          INTERFACE 
            SUBROUTINE SORTTEMPLATE(IMULT)
              INTEGER(KIND=4), INTENT(IN) :: IMULT
            END SUBROUTINE SORTTEMPLATE
          END INTERFACE 
        END MODULE SORTTEMPLATE__genmod
